### PR TITLE
fixed capture download optional format argument

### PR DESCRIPTION
**Pull request by mdilloniol**

### CODE REVIEW

**Comment by nwidger** [comment]
Thanks for the PR @mdilloniol.  Your solution works but I think it would be better to simply hardcode the `format` parameter to be `cap` and not have a `format` parameter to the `download` method, since no other value for `format` makes since in that context.  If you wouldn't mind fixing that up I'll merge the PR.

**Comment by nwidger** [comment]
I'm not sure if you're using `pip` to install the package or not, but I just pushed out a 0.4.8 release which has your fix in it.

It's good to know someone is using this!  Please let me know if you have any questions/feedback, and I'd love to hear about what you're using the package for.

**Comment by mdilloniol** [comment]
Thanks for pushing the new release! I'll definitely let you know if I have feedback. Currently I'm just using this to bulk download captures and logs from a CDRouter in .pcapng and .txt format.

**Comment by nwidger** [comment]
Good to know!  If that's the case you may find it easier to use the result logdir archive API endpoint, which gives you a .zip or .tgz archive containing all the logs and captures for a result:

https://support.qacafe.com/cdrouter-web-api/results/#download-logdir-archive
https://cdrouterpy.readthedocs.io/en/latest/reference.html#cdrouter.results.ResultsService.download_logdir_archive

**Pull request merged**
